// frontend/poc-app/src/components/BookList.vue
<template>
	<div>
		<h4 v-if="loading">Loading ...</h4>
		<book-item v-for="book in books"
		v-bind:key="book.id"
		v-bind:book="book"></book-item>
	</div>
</template>

<script>
	import { BOOKS_QUERY } from '../constants/graphql.js'
	import BookItem from './BookItem.vue'

	export default {
		name: 'BookList',
		components: {
			BookItem
		},
		data () {
			return {
				books:[],
				
				loading: 0
			}
		},
		apollo: {
			books: {
				query: BOOKS_QUERY,
				loadingKey: 'loading',
			},
		},
	};

	// export default {
	// 	name: 'BookList',
	// 	data:  function (){
	// 		return {
	// 			books: [],
	// 			loading: 0,
	// 		}
	// 	},
	// 	apollo: {
	// 		books: {
	// 			query: BOOKS_QUERY,
	// 			pollInterval: 300,
	// 			loadingKey: 'loading',
	// 		}
	// 	},
	// 	components: {
	// 		BookItem
	// 	}
	// };
	// export default {
	// 	name: 'BookList',
	// 	data:  function (){
	// 		return {
	// 			books: [{bookTitle:'testing'}],
	// 			loading: 0,
	// 		}
	// 	},
	// 	apollo: {
	// 		books () {
	// 			return{
	// 				query: BOOKS_QUERY,
	// 				pollInterval: 300,
	// 				loadingKey: 'loading',
	// 			}
	// 		}
	// 	},
	// 	components: {
	// 		BookItem
	// 	}
	// };

</script>

// frontend/react-frontend/src/components/BookList.js
import React, { Component } from 'react';
import { gql } from 'apollo-boost';
import { graphql } from 'react-apollo';
// import Book from './Book';

const getBooksQuery = gql `
	{
		books{
			id
			bookTitle
			genre
			author {
				firstName
			}
		}
	}
`

class BookList extends Component {
	displayBooks(){
		var data = this.props.data;
		if(data.loading){
			return(<div> Loading books...</div>);
		} else {
			return data.books.map(book => {
				return(
					<li key={book.id}>{book.bookTitle} - {book.genre} - {book.author.firstName}</li>
				);
			})
		}
	}
	render () {
		return(
			<div>
				<ul id="book-list">
					{ this.displayBooks() }
				</ul>
			</div>
		)
	}
}

// export default graphql(BOOKLIST_QUERY, {name: 'bookQuery'}) (BookList);
export default graphql(getBooksQuery) (BookList);
